clear;
clc;
QuadParameter;
PS_I;
Omega_I = Omega;
init_I = init;
data_I = data;
PS_II;
Omega_II = Omega;
init_II = init;
data_II = data;
PS_III;
Omega_III = Omega;
init_III = init;
data_III = data;PS_III;
PS_IV;
Omega_IV = Omega;
Omega_IV(3) = Omega_IV(1);
Omega_IV(1) = Omega_IV(2);
init_IV = init;
% data_IV = data;
% PS_V;
% Omega_V = Omega;
% init_V = init;
% data_V = data;