clc;
clear;
QuadConstants;
load('31-Mar-2022-18-15-05-LQIDG_3DOF1005.mat'); % stable;
weighting_matrix = XOpt;
Roll_OpenLoop_LQIDG_solver;
LQIDG_openloop_roll_s = LQIDG_openloop_roll;
Pitch_OpenLoop_LQIDG_solver;
LQIDG_openloop_pitch_s = LQIDG_openloop_pitch;
Yaw_OpenLoop_LQIDG_solver;
LQIDG_openloop_yaw_s = LQIDG_openloop_yaw;
load('31-Mar-2022-02-18-21-LQIDG_3DOF10005.mat');
weighting_matrix = XOpt;
Roll_OpenLoop_LQIDG_solver;
Pitch_OpenLoop_LQIDG_solver;
Yaw_OpenLoop_LQIDG_solver;