QuadConstants;
A = [0 1;
    B1 0];
B = [0; 1];
C = eye(2);
D = zeros(2, 1);
weighting_matrix = XOpt;
Q1 = weighting_matrix(1)^10;
Q2 = weighting_matrix(2)^10;
R  = weighting_matrix(3)^10;
I  = weighting_matrix(4)^10;
Q = diag([Q1, Q2]);
[~, K, ~] = icare(A, B, Q, R);