load('../Scenario_IX');
AHRS = -AHRS;
roll  = AHRS(:, 1);
pitch = AHRS(:, 2);
p     = AHRS(:, 4);
q     = AHRS(:, 5);
data = [roll ,pitch ,p ,q];
Omega_IX = Omega(1, :);
data_IX = data(331:341, :);
init_IX = data_IX(1, :);
time_step = 0.02;
time_IX = 0:time_step:(length(data_IX)-1)*time_step;
time_IX = time_IX'; 