clear;
clc;
QuadConstants;
PS_I;
Omega_I = Omega_data;
data_I = data;
init_I = data(1, :);
PS_II;
Omega_II = Omega_data;
data_II = data;
init_II = data(1, :);
PS_III;
Omega_III = Omega_data;
data_III = data;
init_III = data(1, :);
PS_IV;
Omega_IV = Omega_data;
Omega_IV(3) = Omega_IV(1);
Omega_IV(1) = Omega_IV(2);
data_IV = data;
init_IV = data(1, :);
PS_V;
Omega_V = Omega_data;
data_V = data;
init_V = data(1, :);